"""VerySadai image generation; generated bytes stay outside model text and metrics."""
from __future__ import annotations

import os
import base64
from pathlib import Path
from uuid import uuid4
import httpx

from ..config import PROJECT_ROOT
from ..pipeline_types import GeneratedImage, ToolKind, ToolRequest, ToolResult

IMAGE_MODEL = "gpt-image-2.5-sunburst"
IMAGE_ENDPOINT = "https://verysadai.com/v1/images/generations"
IMAGE_DIRECTORY = PROJECT_ROOT / ".pi" / "generated-images"


async def generate_image(request: ToolRequest) -> ToolResult:
    key = os.getenv("VERYSADAI_API_KEY")
    if not key:
        return ToolResult(ToolKind.IMAGE_GENERATION, "unavailable",
                          context="[生图失败] 服务密钥未配置，本轮没有生成图片。", error="image_key_missing")
    async with httpx.AsyncClient(timeout=300.0) as client:
        response = await client.post(
            IMAGE_ENDPOINT,
            headers={"Authorization": f"Bearer {key}", "Accept-Encoding": "identity"},
            json={"model": IMAGE_MODEL, "prompt": request.query, "n": 1,
                  "quality": "low", "size": "1024x1024", "output_format": "png"},
        )
        response.raise_for_status()
        payload = response.json()
    item = payload["data"][0]
    image = GeneratedImage(item["b64_json"], request.query, IMAGE_MODEL)
    IMAGE_DIRECTORY.mkdir(parents=True, exist_ok=True)
    saved_path = IMAGE_DIRECTORY / f"{uuid4().hex}.png"
    saved_path.write_bytes(base64.b64decode(image.base64_data))
    usage = payload.get("usage") or {}
    return ToolResult(
        ToolKind.IMAGE_GENERATION, "ok",
        context=f"[生图结果] 已按提示词生成一张图片：{request.query}。图片将随本条回复发送；没有读取生成图的画面细节。",
        metadata={"model": IMAGE_MODEL, "quality": "low", "actual_size": item.get("size") or payload.get("size", ""),
                  "saved_path": str(saved_path),
                  "input_tokens": usage.get("input_tokens"), "output_tokens": usage.get("output_tokens")},
        generated_images=(image,),
    )
