"""VerySadai image generation; generated bytes stay outside model text and metrics."""
from __future__ import annotations

import os
import time
import base64
from pathlib import Path
from uuid import uuid4
import httpx

from ..config import PROJECT_ROOT
from ..pipeline_types import GeneratedImage, ToolKind, ToolRequest, ToolResult

IMAGE_MODEL = "gpt-image-2.5-sunburst"
IMAGE_ENDPOINT = "https://verysadai.com/v1/images/generations"
IMAGE_DIRECTORY = PROJECT_ROOT / ".pi" / "generated-images"
# Generation runs inside the group's serialized flow; a long wait blocks every
# other reply in that group, so the deadline is kept well under 300s.
IMAGE_TIMEOUT_SECONDS = 120.0
USER_COOLDOWN_SECONDS = 90.0
CHAT_DAILY_LIMIT = 20
RETENTION_SECONDS = 7 * 86400

_last_by_user: dict[tuple[int, int], float] = {}
_daily_by_chat: dict[tuple[int, str], int] = {}


def _rate_limit_reason(group_id: int, user_id: int, now: float) -> str:
    if now - _last_by_user.get((group_id, user_id), 0.0) < USER_COOLDOWN_SECONDS:
        return "刚画完一张，同一个人要隔一会儿再画"
    if _daily_by_chat.get((group_id, time.strftime("%Y-%m-%d", time.localtime(now))), 0) >= CHAT_DAILY_LIMIT:
        return "今天这里画得太多了，明天再画"
    return ""


POLITICAL_BLOCK_CONTEXT = "[生图拒绝] 这个画面涉及中国政治人物，不画；本轮没有生成图片。"


async def _depicts_china_political_figure(text: str) -> bool:
    """No Chinese (incl. HK/Macau/Taiwan) political figures, by name, nickname or allusion."""
    from ..political_guard import political_candidates, sanitize_political_output_detail

    if sanitize_political_output_detail(text, contextual_keys=()).guarded:
        return True  # hard names: 习近平, 毛主席, 江泽民 ...
    try:
        from ..jev_client import JevClient, _optional_noul

        client = JevClient()
        try:
            data = await client.evaluate(
                state=f"【画图请求】{text[:600]}",
                questions={"china_political_figure": {"type": "noul", "instructions": (
                    "这个画图请求是否要画出或影射中国（含港澳台）的政治人物：现任或历史领导人、官员、政党人物、政治异见人士；"
                    "包括真名、外号、谐音、梗图称呼，以及明显指向某位领导人的外貌、职务或场景描述。"
                    "其他国家的政治人物、动漫角色、普通人物和动物为 false。"
                )}},
            )
        finally:
            await client.aclose()
        score = _optional_noul(data, "china_political_figure")
    except Exception:
        score = None
    if score is None:
        # Judge unavailable: ambiguous names (维尼, 教员 ...) fail closed.
        return bool(political_candidates(text))
    # Live calibration: allusions 0.35-0.99, ordinary requests 0.01-0.02.
    return score >= 0.30


def _prune_old_images(now: float) -> None:
    for path in IMAGE_DIRECTORY.glob("*.png"):
        try:
            if now - path.stat().st_mtime > RETENTION_SECONDS:
                path.unlink()
        except OSError:
            continue


async def generate_image(request: ToolRequest) -> ToolResult:
    key = os.getenv("VERYSADAI_API_KEY")
    if not key:
        return ToolResult(ToolKind.IMAGE_GENERATION, "unavailable",
                          context="[生图失败] 服务密钥未配置，本轮没有生成图片。", error="image_key_missing")
    request_text = "\n".join(
        part for part in (str(request.arguments.get("source_text") or ""), request.query) if part
    )
    if await _depicts_china_political_figure(request_text):
        return ToolResult(ToolKind.IMAGE_GENERATION, "refused", context=POLITICAL_BLOCK_CONTEXT,
                          error="image_political_figure")
    group_id = int(request.arguments.get("group_id") or 0)
    user_id = int(request.arguments.get("user_id") or 0)
    now = time.time()
    limited = _rate_limit_reason(group_id, user_id, now)
    if limited:
        return ToolResult(ToolKind.IMAGE_GENERATION, "rate_limited",
                          context=f"[生图暂停] {limited}，本轮没有生成图片。", error="image_rate_limited")
    _last_by_user[(group_id, user_id)] = now
    day_key = (group_id, time.strftime("%Y-%m-%d", time.localtime(now)))
    _daily_by_chat[day_key] = _daily_by_chat.get(day_key, 0) + 1
    async with httpx.AsyncClient(timeout=IMAGE_TIMEOUT_SECONDS) as client:
        response = await client.post(
            IMAGE_ENDPOINT,
            headers={"Authorization": f"Bearer {key}", "Accept-Encoding": "identity"},
            json={"model": IMAGE_MODEL, "prompt": request.query, "n": 1,
                  "quality": "low", "size": "1024x1024", "output_format": "png"},
        )
        response.raise_for_status()
        payload = response.json()
    item = payload["data"][0]
    image = GeneratedImage(item["b64_json"], request.query, IMAGE_MODEL)
    IMAGE_DIRECTORY.mkdir(parents=True, exist_ok=True)
    saved_path = IMAGE_DIRECTORY / f"{uuid4().hex}.png"
    saved_path.write_bytes(base64.b64decode(image.base64_data))
    _prune_old_images(now)
    usage = payload.get("usage") or {}
    return ToolResult(
        ToolKind.IMAGE_GENERATION, "ok",
        context=f"[生图结果] 已按提示词生成一张图片：{request.query}。图片将随本条回复发送；没有读取生成图的画面细节。",
        metadata={"model": IMAGE_MODEL, "quality": "low", "actual_size": item.get("size") or payload.get("size", ""),
                  "saved_path": str(saved_path),
                  "input_tokens": usage.get("input_tokens"), "output_tokens": usage.get("output_tokens")},
        generated_images=(image,),
    )
